application: rohit-php-re
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /(.+\.(html|css|php|gif|png|jpg))$
  static_files: \1
  upload: .+\.(html|css|php|gif|png|jpg)$
  application_readable: true

# PHP Scriptbestanden.
- url: /(.+\.php)$
  script: \1
  
- url: /.*
  static_files: index.php
  upload: index.php
  application_readable: true
